/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_HW3REF2CLIENT_H_
#define JSONRPC_CPP_STUB_HW3REF2CLIENT_H_

#include <jsonrpccpp/client.h>

class hw3ref2Client : public jsonrpc::Client
{
    public:
        hw3ref2Client(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value upload(const Json::Value& updating_json) 
        {
            Json::Value p;
            p["updating_json"] = updating_json;
            Json::Value result = this->CallMethod("upload",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value question(const Json::Value& search_clause) 
        {
            Json::Value p;
            p["search_clause"] = search_clause;
            Json::Value result = this->CallMethod("question",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_HW3REF2CLIENT_H_
