/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_HW3REF2SERVER_H_
#define JSONRPC_CPP_STUB_HW3REF2SERVER_H_

#include <jsonrpccpp/server.h>

class hw3ref2Server : public jsonrpc::AbstractServer<hw3ref2Server>
{
    public:
        hw3ref2Server(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<hw3ref2Server>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("upload", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "updating_json",jsonrpc::JSON_OBJECT, NULL), &hw3ref2Server::uploadI);
            this->bindAndAddMethod(jsonrpc::Procedure("question", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "search_clause",jsonrpc::JSON_OBJECT, NULL), &hw3ref2Server::questionI);
        }

        inline virtual void uploadI(const Json::Value &request, Json::Value &response)
        {
            response = this->upload(request["updating_json"]);
        }
        inline virtual void questionI(const Json::Value &request, Json::Value &response)
        {
            response = this->question(request["search_clause"]);
        }
        virtual Json::Value upload(const Json::Value& updating_json) = 0;
        virtual Json::Value question(const Json::Value& search_clause) = 0;
};

#endif //JSONRPC_CPP_STUB_HW3REF2SERVER_H_
